version: '2'
services:
  schoolmanagementsystem-app:
    image: schoolmanagementsystem
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://schoolmanagementsystem-mysql:3306/schoolmanagementsystem?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://schoolmanagementsystem-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://schoolmanagementsystem-elasticsearch:9200
    ports:
      - 8080:8080
  schoolmanagementsystem-mysql:
    extends:
      file: mysql.yml
      service: schoolmanagementsystem-mysql
  schoolmanagementsystem-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: schoolmanagementsystem-elasticsearch
